"""empty message

Revision ID: 1e9b20242827
Revises: 98e80f255ef1
Create Date: 2018-12-16 14:41:33.581239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9b20242827'
down_revision = '98e80f255ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
